### ISSUE TITLE
Standalone lib

### ISSUE THREAD

**Issue by CoWayger** [markeasting/THREE-XPBD#2]
Hi, this project looks awesome!

Would it be possible to create standalone lib for physics and make npm package from it? It would make implementing into own renderers or other libs a breeze.

**Comment by markeasting** [comment]
Hi there,

Thanks for taking an interest in this project! 

I have to say, this project is pretty much in an 'alpha' state. There is still much optimization to be done and many features to be added. 

You might want to take a look at these other (production-ready) projects:

- [Ammo.js](https://github.com/kripken/ammo.js)
- [Cannon.js](https://github.com/schteppe/cannon.js)
- [Oimo.js](https://github.com/lo-th/Oimo.js)

If you still wish to use my code in your project, please let me know!

**Comment by CoWayger** [comment]
I like Cannon.js the most, but its based on standard physics solvers. It does not support threading (SharedWorkers / Shared Arrays). Also project it's abandoned. I will definitely tinker with this repo as XPBD is a beast to tame :)

**Comment by markeasting** [comment]
Alright :ok_hand: 

To set up the basics, you can copy the [XPBDSolver](https://github.com/markeasting/THREE-XPBD/blob/master/src/physics/solver/XPBDSolver.ts) class. Just remove the GUI related stuff from the constructor.

You can also take a look at the [World](https://github.com/markeasting/THREE-XPBD/blob/master/src/physics/World.ts) class, which manages bodies and constraints. This also has some GUI code that you need to remove. 

I'll refactor the codebase at some point - it's currently tightly coupled to the GUI and scene manager components.

**Comment by markeasting** [comment]
https://github.com/markeasting/THREE-XPBD/issues/3
